//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/CutsceneInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CutsceneInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CutsceneInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CutsceneInput"",
    ""maps"": [
        {
            ""name"": ""Continue"",
            ""id"": ""0278c9ea-9f8a-4f05-9fc2-301ad595e934"",
            ""actions"": [
                {
                    ""name"": ""Skip"",
                    ""type"": ""Button"",
                    ""id"": ""f7ae782e-3684-4e05-b7c5-8bcc3520f054"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0fe4447a-4bce-4361-ac4f-ff9d263f04a5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe27b496-9bb7-41e8-ae50-ff28c6726a39"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Continue
        m_Continue = asset.FindActionMap("Continue", throwIfNotFound: true);
        m_Continue_Skip = m_Continue.FindAction("Skip", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Continue
    private readonly InputActionMap m_Continue;
    private IContinueActions m_ContinueActionsCallbackInterface;
    private readonly InputAction m_Continue_Skip;
    public struct ContinueActions
    {
        private @CutsceneInput m_Wrapper;
        public ContinueActions(@CutsceneInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Skip => m_Wrapper.m_Continue_Skip;
        public InputActionMap Get() { return m_Wrapper.m_Continue; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ContinueActions set) { return set.Get(); }
        public void SetCallbacks(IContinueActions instance)
        {
            if (m_Wrapper.m_ContinueActionsCallbackInterface != null)
            {
                @Skip.started -= m_Wrapper.m_ContinueActionsCallbackInterface.OnSkip;
                @Skip.performed -= m_Wrapper.m_ContinueActionsCallbackInterface.OnSkip;
                @Skip.canceled -= m_Wrapper.m_ContinueActionsCallbackInterface.OnSkip;
            }
            m_Wrapper.m_ContinueActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Skip.started += instance.OnSkip;
                @Skip.performed += instance.OnSkip;
                @Skip.canceled += instance.OnSkip;
            }
        }
    }
    public ContinueActions @Continue => new ContinueActions(this);
    public interface IContinueActions
    {
        void OnSkip(InputAction.CallbackContext context);
    }
}
